fix: :bug: Potential fix for CI/CD

diff --git a/.github/workflows/CI_CD_package_box.yml b/.github/workflows/CI_CD_package_box.yml
--- a/.github/workflows/CI_CD_package_box.yml
+++ b/.github/workflows/CI_CD_package_box.yml
@@ -16,6 +16,11 @@ jobs:
         run: |
           ASSET_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
             | jq -r '.assets[] | select(.name | endswith(".box")) | .browser_download_url')
+          
+          if [ "$ASSET_URL" == "null" ] || [ -z "$ASSET_URL" ]; then
+            echo "Error: No se encontró ningún archivo .box en esta Release."
+            exit 1
+          fi
           echo "url=$ASSET_URL" >> $GITHUB_OUTPUT
 
       - name: Download Box from Release
@@ -29,5 +34,6 @@ jobs:
           box: "foodhub"
           version: "${{ github.event.release.tag_name }}"
           provider: "virtualbox"
-          token: "${{ secrets.VAGRANT_CLOUD_TOKEN }}"
+          hcp_client_id: ${{ secrets.HCP_CLIENT_ID }}
+          hcp_client_secret: ${{ secrets.HCP_CLIENT_SECRET }}
           file: "latest_box.box"
